pub mod api_tracker;
pub mod budget;
pub mod capability;
pub mod config;
pub mod content_sensitivity;
pub mod rate_limit;
pub mod embedding;
pub mod error;
pub mod identity;
pub mod mesh;
pub mod provider_catalog;
pub mod provider_meta;
pub mod segment;
pub mod sensorium;
pub mod succession;
pub mod threading;
pub mod tier;

pub use api_tracker::{ApiTracker, ApiUsageSnapshot};
pub use budget::{BudgetState, BudgetPressure, BudgetThresholds};
pub use capability::{CapabilityState, CognitiveTier};
pub use content_sensitivity::{ContentSensitivity, SensitivityScan};
pub use rate_limit::{RateLimitState, RATE_LIMIT_NEAR_THRESHOLD};
pub use mesh::{AttestationFields, CapabilityAttestation, MeshRole, RoleMesh, VerifiedAttestation};
pub use provider_catalog::{known_providers, provider_trust_map};
pub use provider_meta::{CostTier, DataPolicy, OwnershipRisk, ProviderTrustProfile, QualityTier, SpeedTier};
pub use succession::SuccessionPolicy;
pub use config::{AnimusConfig, CortexConfig, EmbeddingConfig, EmbeddingProviderKind, FederationConfig, HealthConfig, InterfaceConfig, MnemosConfig, NatsChannelConfig, PrincipalConfig, PrincipalRole, QualityGateConfig, SensoriumConfig, SnapshotConfig, VectorFSConfig};
pub use embedding::EmbeddingService;
pub use error::{AnimusError, Result};
pub use identity::{AnimusIdentity, EventId, GoalId, InstanceId, PolicyId, SegmentId, SnapshotId, ThreadId};
pub use segment::{Content, DecayClass, Principal, Segment, Source, Tier};
pub use threading::{ThreadStatus, Signal, SignalPriority};
pub use tier::TierConfig;
