pub mod api_tracker;
pub mod capability;
pub mod config;
pub mod embedding;
pub mod error;
pub mod identity;
pub mod segment;
pub mod sensorium;
pub mod threading;
pub mod tier;

pub use api_tracker::{ApiTracker, ApiUsageSnapshot};
pub use capability::{CapabilityState, CognitiveTier};
pub use config::{AnimusConfig, CortexConfig, EmbeddingConfig, EmbeddingProviderKind, FederationConfig, HealthConfig, InterfaceConfig, MnemosConfig, NatsChannelConfig, PrincipalConfig, PrincipalRole, QualityGateConfig, SensoriumConfig, SnapshotConfig, VectorFSConfig};
pub use embedding::EmbeddingService;
pub use error::{AnimusError, Result};
pub use identity::{AnimusIdentity, EventId, GoalId, InstanceId, PolicyId, SegmentId, SnapshotId, ThreadId};
pub use segment::{Content, DecayClass, Principal, Segment, Source, Tier};
pub use threading::{ThreadStatus, Signal, SignalPriority};
pub use tier::TierConfig;
